//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Voiture
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "svp ce champ ne doit pas etre vide")]
        public string imma { get; set; }

        [Required(ErrorMessage = "svp ce champ ne doit pas etre vide")]
        public Nullable<int> capacite { get; set; }
        [Required(ErrorMessage = "svp ce champ ne doit pas etre vide")]
        public Nullable<decimal> charge_diesl { get; set; }
        [Required(ErrorMessage = "svp ce champ ne doit pas etre vide")]
        public Nullable<decimal> kilometrage { get; set; }
        [Required(ErrorMessage = "svp ce champ ne doit pas etre vide")]
        public Nullable<decimal> max_vitesse { get; set; }
        [Required(ErrorMessage = "svp ce champ ne doit pas etre vide")]
        public Nullable<decimal> montant { get; set; }
        [Required(ErrorMessage = "svp ce champ ne doit pas etre vide")]
        public Nullable<int> Marque { get; set; }
        [Required(ErrorMessage = "svp ce champ ne doit pas etre vide")]
        public Nullable<int> Module { get; set; }
        [Required(ErrorMessage = "svp ce champ ne doit pas etre vide")]
        public Nullable<int> Propretaire { get; set; }
        [Required(ErrorMessage = "svp ce champ ne doit pas etre vide")]
        public Nullable<int> Categorie { get; set; }
        public Nullable<bool> GPS { get; set; }
        public  string imageLocation { get; set; }
        [Required(ErrorMessage = "svp ce champ ne doit pas etre vide")]

        public virtual Categorie Categorie1 { get; set; }
        [Required(ErrorMessage = "svp ce champ ne doit pas etre vide")]
        public virtual Marque Marque1 { get; set; }
        [Required(ErrorMessage = "svp ce champ ne doit pas etre vide")]
        public virtual Module Module1 { get; set; }
        [Required(ErrorMessage = "svp ce champ ne doit pas etre vide")]
        public virtual Propretaire Propretaire1 { get; set; }
    }
}
